"""create mcp_credentials table

Revision ID: dc0837148950
Revises: e0e2a6e8735d
Create Date: 2026-04-25 00:18:05.589162

"""
from alembic import op
import sqlalchemy as sa



revision = 'dc0837148950'
down_revision = 'e0e2a6e8735d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.String(length=50), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_credentials_user_id'), 'mcp_credentials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mcp_credentials_user_id'), table_name='mcp_credentials')
    op.drop_table('mcp_credentials')
    # ### end Alembic commands ###
