"""add google_id and register models

Revision ID: e0e2a6e8735d
Revises: 266c84ca8329
Create Date: 2026-04-24 10:06:59.415668

"""
from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = 'e0e2a6e8735d'
down_revision = '266c84ca8329'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('session_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.drop_column('execution_plans', 'tasks')
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'clerk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('clerk_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.drop_column('users', 'google_id')
    op.add_column('execution_plans', sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'session_id')
    # ### end Alembic commands ###
